/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(voter)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(voter)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(voter)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(voter)'}/results` | `/results`; params?: Router.UnknownInputParams; } | { pathname: `${'/(voter)'}/election/[id]` | `/election/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(voter)'}/vote/[id]` | `/vote/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(voter)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(voter)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(voter)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(voter)'}/results` | `/results`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(voter)'}/election/[id]` | `/election/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(voter)'}/vote/[id]` | `/vote/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(voter)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(voter)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(voter)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(voter)'}/results${`?${string}` | `#${string}` | ''}` | `/results${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(voter)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(voter)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(voter)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(voter)'}/results` | `/results`; params?: Router.UnknownInputParams; } | `${'/(voter)'}/election/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/election/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(voter)'}/vote/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/vote/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(voter)'}/election/[id]` | `/election/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(voter)'}/vote/[id]` | `/vote/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
